version: "3.8"
services:
  broker:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - "~/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro"
      - "~/mosquitto/data:/mosquitto/data"
      - "~/mosquitto/log:/mosquitto/log"
